// client/src/layouts/AdminLayout.jsx
import React from 'react';
import { Outlet } from 'react-router-dom';
import AdminSidebar from '../components/AdminSidebar';
import ScrollToTopButton from '../components/ScrollToTopButton';

export default function AdminLayout() {
  return (
    <div className="flex min-h-screen bg-gray-100">
      <AdminSidebar />
      <div className="flex-1 ml-64 p-8">
        <Outlet />
      </div>
      <ScrollToTopButton />
    </div>
  );
}

// client/src/app/layouts/admin-layout/admin-layout.component.ts
import { Component } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import { AdminSidebarComponent } from '../../components/admin-sidebar/admin-sidebar.component';

@Component({
    selector: 'app-admin-layout',
    standalone: true,
    imports: [RouterOutlet, AdminSidebarComponent],
    template: `
    <div class="flex min-h-screen bg-gray-100">
      <app-admin-sidebar></app-admin-sidebar>
      <div class="flex-1 ml-64 p-8">
        <router-outlet></router-outlet>
      </div>
    </div>
  `
})
export class AdminLayoutComponent { }
